export const datos = [
    {
        id: "0",
        nombre: "Alejandra",
        apellidos: "Salazar Bengoechea",
        nacimiento: "31/12/1985",
        genero: "Femenino",
        nacionalidad: "España",
        ciudad: "Madrid",
        ranking: 1,
        brazodominante: "Diestro",
        compañerx: "Gemma Triay",
        altura: 1.68,
        posicion: "Revés",
        URL: "https://www.worldpadeltour.com/media-content/2022/05/alejandra-salazar-bengoechea-c50aaf0cc5-220x260.JPG",
    },
    {
        id: "1",
        nombre: "Arturo",
        apellidos: "Aguilera González",
        nacimiento: "15/12/2001",
        genero: "Masculino",
        nacionalidad: "España",
        ciudad: "Málaga",
        ranking: 1,
        brazodominante: "Zurdo",
        compañerx: null,
        altura: 1.78,
        posicion: "Derecha",
        URL: "https://avatars.githubusercontent.com/u/77731178?v=4",
    },
    {
        id: "2",
        nombre: "Ignacio",
        apellidos: "Ávila Reyes",
        nacimiento: "24/05/2001",
        genero: "Masculino",
        nacionalidad: "España",
        ciudad: "Málaga",
        ranking: 1,
        brazodominante: "Diestro",
        compañerx: null,
        altura: 1.81,
        posicion: "Derecha",
        URL: "https://media-exp1.licdn.com/dms/image/C5603AQHLNZIupGcfcQ/profile-displayphoto-shrink_200_200/0/1621530394680?e=1654128000&v=beta&t=gEeG6JbB7BCrWxfCvC3GjqumJWkmP8QtdMzFyiNGA7I",
    },
    {
        id: "3",
        nombre: "Maria José",
        apellidos: "García Tobaruela",
        nacimiento: "05/06/2001",
        genero: "Femenino",
        nacionalidad: "España",
        ciudad: "Algeciras",
        ranking: 1,
        brazodominante: "Diestro",
        compañerx: null,
        altura: 1.7,
        posicion: "Revés",
        URL: "https://static1.diariosur.es/www/multimedia/202202/24/media/cortadas/titulo1-RAAr6qsrMBfxN8Ept9wNbfO-624x385@Diario%20Sur.jpg",
    },
    {
        id: "4",
        nombre: "Manuel",
        apellidos: "Castillo Sancho",
        nacimiento: "09/05/2001",
        genero: "Masculino",
        nacionalidad: "España",
        ciudad: "Málaga",
        ranking: 1,
        brazodominante: "Diestro",
        compañerx: null,
        altura: 1.8,
        posicion: "Revés",
        URL: "https://ta.azureedge.net/p/images/usuarios/l/PuUea4dH2EiTpjcwkX6kQqKYiSWLHvZH0.jpg/600x600cut/",
    },
    {
        id: "5",
        nombre: "Alejandro",
        apellidos: "Rey Leyva",
        nacimiento: "28/11/2001",
        genero: "Masculino",
        nacionalidad: "España",
        ciudad: "Málaga",
        ranking: 1,
        brazodominante: "Diestro",
        compañerx: null,
        altura: 1.79,
        posicion: "Derecha",
        URL: "https://media-exp1.licdn.com/dms/image/C4D03AQGWJHaQqGYedA/profile-displayphoto-shrink_200_200/0/1613920654890?e=1655337600&v=beta&t=IE9cYXSLS4pBRgmoAis07QVhi7QEUQWRJNvwk47YulA",
    },
    {
        id: "6",
        nombre: "Beatriz",
        apellidos: "González Fernández",
        nacimiento: "23/11/2001",
        genero: "Femenino",
        nacionalidad: "España",
        ciudad: "Málaga",
        ranking: 1,
        brazodominante: "Diestro",
        compañerx: null,
        altura: 1.74,
        posicion: "Revés",
        URL: "https://www.radiomarcabarcelona.com/wp-content/uploads/2020/07/Bea-Gonz%C3%A1lez-.jpg",
    },
    {
        id: "7",
        nombre: "Marta",
        apellidos: "Ortega Gallego",
        nacimiento: "14/02/1997",
        genero: "Femenino",
        nacionalidad: "España",
        ciudad: "Madrid",
        ranking: 1,
        brazodominante: "Diestro",
        compañerx: null,
        altura: 1.7,
        posicion: "Derecha",
        URL: "https://www.streetpadel.com/blog/wp-content/uploads/marta-ortega.jpg",
    },
];
