export const jugadores = [
    {
        id: "1",
        nombre: "Alejandra",
        apellidos: "Salazar Bengoechea",
        nacimiento: "31/12/1985",
        genero: "Femenino",
        nacionalidad: "ar",
        ciudad: "Madrid",
        ranking: 1,
        brazodominante: "Diestro",
        compañerx: "Gemma Triay",
        altura: 1.68,
        posicion: "Revés",
        URL: "https://www.worldpadeltour.com/media-content/2022/05/alejandra-salazar-bengoechea-c50aaf0cc5-220x260.JPG",
    },
    {
        id: "2",
        nombre: "Arturo",
        apellidos: "Aguilera González",
        nacimiento: "15/12/2001",
        genero: "Masculino",
        nacionalidad: "at",
        ciudad: "Málaga",
        ranking: 1,
        brazodominante: "Zurdo",
        compañerx: null,
        altura: 1.78,
        posicion: "Derecha",
        URL: "https://avatars.githubusercontent.com/u/77731178?v=4",
    },
    {
        id: "3",
        nombre: "Ignacio",
        apellidos: "Ávila Reyes",
        nacimiento: "24/05/2001",
        genero: "Masculino",
        nacionalidad: "it",
        ciudad: "Cabra",
        ranking: 1,
        brazodominante: "Diestro",
        altura: 1.81,
        posicion: "Derecha",
        URL: "https://avatars.githubusercontent.com/u/77730975?v=4",
    },
    {
        id: "4",
        nombre: "Maria José",
        apellidos: "García Tobaruela",
        nacimiento: "05/06/2001",
        genero: "Femenino",
        nacionalidad: "ec",
        ciudad: "Algeciras",
        ranking: 1,
        brazodominante: "Diestro",
        altura: 1.7,
        posicion: "Revés",
        URL: "https://pps.whatsapp.net/v/t61.24694-24/169338710_508515597560794_4871751170178344193_n.jpg?ccb=11-4&oh=62099b9f108def9f8776397967386df5&oe=62AC5193",
    },
    {
        id: "5",
        nombre: "Manuel",
        apellidos: "Castillo Sancho",
        nacimiento: "09/05/2001",
        genero: "Masculino",
        nacionalidad: "es",
        ciudad: "Málaga",
        ranking: 1,
        brazodominante: "Diestro",
        altura: 1.8,
        posicion: "Revés",
        URL: "https://ta.azureedge.net/p/images/usuarios/l/PuUea4dH2EiTpjcwkX6kQqKYiSWLHvZH0.jpg/600x600cut/",
    },
    {
        id: "6",
        nombre: "Alejandro",
        apellidos: "Rey Leyva",
        nacimiento: "28/11/2001",
        genero: "Masculino",
        nacionalidad: "es",
        ciudad: "Málaga",
        ranking: 1,
        brazodominante: "Diestro",
        altura: 1.79,
        posicion: "Derecha",
        URL: "https://media-exp1.licdn.com/dms/image/C4D03AQGWJHaQqGYedA/profile-displayphoto-shrink_200_200/0/1613920654890?e=1655337600&v=beta&t=IE9cYXSLS4pBRgmoAis07QVhi7QEUQWRJNvwk47YulA",
    },
    {
        id: "7",
        nombre: "Beatriz",
        apellidos: "González Fernández",
        nacimiento: "23/11/2001",
        genero: "Femenino",
        nacionalidad: "br",
        ciudad: "Málaga",
        ranking: 1,
        brazodominante: "Diestro",
        altura: 1.74,
        posicion: "Revés",
        URL: "https://blog.starvie.com/wp-content/uploads/2022/01/bea-gonzalez-jugadora-padel-starvie-scaled.jpg",
    },
    {
        id: "8",
        nombre: "Marta",
        apellidos: "Ortega Gallego",
        nacimiento: "14/02/1997",
        genero: "Femenino",
        nacionalidad: "ch",
        ciudad: "Madrid",
        ranking: 1,
        brazodominante: "Diestro",
        altura: 1.7,
        posicion: "Derecha",
        URL: "https://www.streetpadel.com/blog/wp-content/uploads/marta-ortega.jpg",
    },
    {
        id: "9",
        nombre: "Juan de Dios",
        apellidos: "Aranda Marín",
        nacimiento: "19/08/2001",
        genero: "Masculino",
        nacionalidad: "ru",
        ciudad: "Cabra",
        ranking: 1,
        brazodominante: "Diestro",
        altura: 1.79,
        posicion: "Revés",
        URL: "https://pps.whatsapp.net/v/t61.24694-24/140527823_2513499295621663_7324396283106123325_n.jpg?ccb=11-4&oh=01_AVxZRPTqBrd1SAHsh31juoChlYwm6uhb8WjZ8vAbDoL5qg&oe=6297AA99",
    },
    {
        id: "10",
        nombre: "Juan Carlos",
        apellidos: "Medina Fernández",
        nacimiento: "20/02/2001",
        genero: "Masculino",
        nacionalidad: "es",
        ciudad: "Rute",
        ranking: 1,
        brazodominante: "Diestro",
        altura: 1.8,
        posicion: "Derecha",
        URL: "https://pps.whatsapp.net/v/t61.24694-24/158959421_240904764906764_6648790570954983653_n.jpg?ccb=11-4&oh=01_AVzOFu6EkvTzV-dBkATzYTaAZytXSMY87QP-AIQrWw0SpQ&oe=62AA80FF",
    },
];
