export const parejas = [
  {
    id: "1",
    TemporadasActivo: 2,
    Entrenador: "Jorge Martínez",
    TopRanking: 1,
    Puntos: "34.250",
    IDjugador1: "1",
    IDjugador2: "8",
    Genero: "Femenino",
  },
  {
    id: "2",
    TemporadasActivo: 2,
    Entrenador: "Jose Ángel",
    TopRanking: 1,
    Puntos: "33.550",
    IDjugador1: "3",
    IDjugador2: "6",
    Genero: "Masculino",
  },
  {
    id: "3",
    TemporadasActivo: 4,
    Entrenador: "Daniel Girela",
    TopRanking: 2,
    Puntos: "28.230",
    IDjugador1: "2",
    IDjugador2: "5",
    Genero: "Masculino",
  },
  {
    id: "4",
    TemporadasActivo: 1,
    Entrenador: "Jessie Cafete",
    TopRanking: 1,
    Puntos: "30.710",
    IDjugador1: "7",
    IDjugador2: "4",
    Genero: "Femenino",
  },
  {
    id: "5",
    TemporadasActivo: 2,
    Entrenador: "Jose Luis",
    TopRanking: 3,
    Puntos: "20.760",
    IDjugador1: "9",
    IDjugador2: "10",
    Genero: "Masculino",
  }
];
