export const partidos = [
    {
        id: "1",
        torneoID: "1",
        fase: "Cuartos de Final",
        idPareja1: "2",
        idPareja2: "3",
        tiempo: "03:04:15",
        resultado: "3/6/6/3/6/4",
        fecha: "21/05/2022",
        genero: "Masculino",
        juezSilla: "Cristóbal",
        breaks: ["3/8", "1/2"],
        winners: ["13", "12"],
        smashes: ["6/6", "2/4"],
        errors: ["11", "10"],
        gold: ["3", "1"],
    },
    {
        id: "2",
        torneoID: "2",
        fase: "Final",
        idPareja1: "1",
        idPareja2: "5",
        tiempo: "02:30:52",
        resultado: "6/1/6/1/-/-",
        fecha: "20/05/2022",
        genero: "Masculino",
        juezSilla: "Cristóbal",
        breaks: ["-/-", "-/-"],
        winners: ["-", "-"],
        smashes: ["-/-", "-/-"],
        errors: ["-", "-"],
        gold: ["-", "-"],
    },
    {
        id: "3",
        torneoID: "3",
        fase: "Final",
        idPareja1: "2",
        idPareja2: "5",
        tiempo: "02:55:37",
        resultado: "3/6/6/2/6/2",
        fecha: "19/05/2022",
        genero: "Femenino",
        juezSilla: "Cristóbal",
        breaks: ["-/-", "-/-"],
        winners: ["-", "-"],
        smashes: ["-/-", "-/-"],
        errors: ["-", "-"],
        gold: ["-", "-"],
    },
    {
        id: "4",
        torneoID: "3",
        fase: "Semifinales",
        idPareja1: "3",
        idPareja2: "4",
        tiempo: "02:15:03",
        resultado: "2/6/6/4/6/1",
        fecha: "18/05/2022",
        genero: "Femenino",
        juezSilla: "Cristóbal",
        breaks: ["-/-", "-/-"],
        winners: ["-", "-"],
        smashes: ["-/-", "-/-"],
        errors: ["-", "-"],
        gold: ["-", "-"],
    },
];
