export const torneos = [
    {
        id: "1",
        nombre: "Brussel Padel Open",
        faseInicial: "Octavos de Final",
        institucion: {
            nombre: "World Padel Tour",
            organizador: "Damm",
            internacional: "Sí",
            sede: "Madrid, España",
            anioFundacion: "2013",
            foto: "https://yt3.ggpht.com/ytc/AKedOLTH56fM6nDBwgN_DlfHicOBmHY7m506EVrpjlAx3A=s900-c-k-c0x00ffffff-no-rj",
        },
        anio: "2022",
        ganadores: { jugador1: "Galán", jugador2: "Lebron" },
        categoria: "Masculino",
        // partidos: [...]
    },
    {
        id: "2",
        nombre: "Piso Naxetee Open",
        faseInicial: "Octavos de Final",
        institucion: {
            nombre: "Plutarco Tour",
            organizador: "Raff Tapas Bar",
            internacional: "No",
            sede: "Málaga, España",
            anioFundacion: "2019",
            foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Universidad_de_M%C3%A1laga.jpg/245px-Universidad_de_M%C3%A1laga.jpg",
        },
        anio: "2022",
        ganadores: { jugador1: "Ávila", jugador2: "Aranda" },
        categoria: "Masculino",
    },
    {
        id: "3",
        nombre: "Series Nacionales Padel",
        faseInicial: "Octavos de Final",
        institucion: {
            nombre: "Federación Nacional de Pádel",
            organizador: "Endesa",
            internacional: "No",
            sede: "Madrid, España",
            anioFundacion: "2018",
            foto: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRM3QmFAiiZDXBMacX_H_Thiwue3Knfu1_14CqvGkxZQHjjoNK_uUtVmWuc3kDmCuIF-VE&usqp=CAU",
        },
        anio: "2022",
        ganadores: { jugador1: "González", jugador2: "Ortega" },
        categoria: "Femenino",
    },
    {
        id: "4",
        nombre: "WPT Master Final",
        faseInicial: "Octavos de Final",
        institucion: {
            id: "1",
            nombre: "World Padel Tour",
            organizador: "Damm",
            internacional: "Sí",
            sede: "Madrid, España",
            anioFundacion: "2013",
            foto: "https://yt3.ggpht.com/ytc/AKedOLTH56fM6nDBwgN_DlfHicOBmHY7m506EVrpjlAx3A=s900-c-k-c0x00ffffff-no-rj",
        },
        anio: "2022",
        ganadores: { jugador1: "Triay", jugador2: "Salazar" },
        categoria: "Femenino",
    },
    {
        id: "5",
        nombre: "Valladolid Master",
        faseInicial: "Octavos de Final",
        institucion: {
            id: "1",
            nombre: "World Padel Tour",
            organizador: "Damm",
            internacional: "Sí",
            sede: "Madrid, España",
            anioFundacion: "2013",
            foto: "https://yt3.ggpht.com/ytc/AKedOLTH56fM6nDBwgN_DlfHicOBmHY7m506EVrpjlAx3A=s900-c-k-c0x00ffffff-no-rj",
        },
        anio: "2021",
        ganadores: { jugador1: "Sánchez ", jugador2: "Capra" },
        categoria: "Masculino",
    },
    {
        id: "6",
        nombre: "Marbella Challenger",
        faseInicial: "Octavos de Final",
        institucion: {
            id: "1",
            nombre: "World Padel Tour",
            organizador: "Damm",
            internacional: "Sí",
            sede: "Madrid, España",
            anioFundacion: "2013",
            foto: "https://yt3.ggpht.com/ytc/AKedOLTH56fM6nDBwgN_DlfHicOBmHY7m506EVrpjlAx3A=s900-c-k-c0x00ffffff-no-rj",
        },
        anio: "2021",
        ganadores: { jugador1: "Rico", jugador2: "González" },
        categoria: "Masculino",
    },
    {
        id: "7",
        nombre: "Cupra Vigo Open",
        faseInicial: "Fase de Grupos",
        institucion: {
            id: "1",
            nombre: "World Padel Tour",
            organizador: "Damm",
            internacional: "Sí",
            sede: "Madrid, España",
            anioFundacion: "2013",
            foto: "https://yt3.ggpht.com/ytc/AKedOLTH56fM6nDBwgN_DlfHicOBmHY7m506EVrpjlAx3A=s900-c-k-c0x00ffffff-no-rj",
        },
        anio: "2021",
        ganadores: { jugador1: "Riera", jugador2: "Llaguno" },
        categoria: "Femenino",
    },
];
