export const torneos = [
  {
    id: "1",
    nombre: "Brussel Padel Open",
    faseInicial: "Octavos de Final",
    institucion: "World Padel Tour",
    ganadores: { jugador1: "Galán", jugador2: "Lebron" },
    categoria: "Masculino",
    anio: "2022",
  },
  {
    id: "2",
    nombre: "Piso Naxetee Open",
    faseInicial: "Octavos de Final",
    institucion: "Plutarco Tour",
    ganadores: { jugador1: "Ávila", jugador2: "Aranda" },
    categoria: "Masculino",
    anio: "2022",
  },
  {
    id: "3",
    nombre: "WPT Master Final",
    faseInicial: "Octavos de Final",
    institucion: "World Padel Tour",
    ganadores: { jugador1: "Triay", jugador2: "Salazar" },
    categoria: "Femenino",
    anio: "2022",
  },
  {
    id: "4",
    nombre: "Cupra Vigo Open",
    faseInicial: "Octavos de Final",
    institucion: "World Padel Tour",
    ganadores: { jugador1: "Riera", jugador2: "Llaguno" },
    categoria: "Femenino",
    anio: "2021",
  },
  {
    id: "5",
    nombre: "Valladolid Master",
    faseInicial: "Octavos de Final",
    institucion: "World Padel Tour",
    ganadores: { jugador1: "Sánchez ", jugador2: "Capra" },
    categoria: "Masculino",
    anio: "2021",
  },
  {
    id: "6",
    nombre: "Marbella Challenger",
    faseInicial: "Octavos de Final",
    institucion: "World Padel Tour",
    ganadores: { jugador1: "Rico", jugador2: "González" },
    categoria: "Masculino",
    anio: "2021",
  },
];
